name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Check Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Check
        run: cargo check --workspace
      - name: Test
        run: cargo test --workspace
      - name: Build binary
        run: cargo build --release --bin sentinel
